MONGODB_HOST: mongodb.vinaymukkamalla.fun
REDIS_HOST: redis.vinaymukkamalla.fun
CATALOGUE_HOST: catalogue.vinaymukkamalla.fun
CART_HOST: cart.vinaymukkamalla.fun
MYSQL_HOST: mysql.vinaymukkamalla.fun
RABBITMQ_HOST: rabbitmq.vinaymukkamalla.fun
USER_HOST: user.vinaymukkamalla.fun
SHIPPING_HOST: shipping.vinaymukkamalla.fun
PAYMENT_HOST: payment.vinaymukkamalla.fun

