MONGODB_HOST: mongodb-{{  env  }}.vinaymukkamalla.fun
REDIS_HOST: redis-{{  env  }}.vinaymukkamalla.fun
CATALOGUE_HOST: catalogue-{{  env  }}.vinaymukkamalla.fun
CART_HOST: cart-{{  env  }}.vinaymukkamalla.fun
MYSQL_HOST: mysql-{{  env  }}.vinaymukkamalla.fun
RABBITMQ_HOST: rabbitmq-{{  env  }}.vinaymukkamalla.fun
USER_HOST: user-{{  env  }}.vinaymukkamalla.fun
SHIPPING_HOST: shipping-{{  env  }}.vinaymukkamalla.fun
PAYMENT_HOST: payment-{{  env  }}.vinaymukkamalla.fun

