[frontend]
172.31.30.111

[mongodb]
#mongodb.vinaymukkamalla.fun
localhost

[redis]
#redis.vinaymukkamalla.fun
localhost

[mysql]
#mysql.vinaymukkamalla.fun
localhost

[rabbitmq]
#rabbitmq.vinaymukkamalla.fun
localhost

[catalogue]
catalogue.vinaymukkamalla.fun

[cart]
cart.vinaymukkamalla.fun

[user]
user.vinaymukkamalla.fun

[shipping]
shipping.vinaymukkamalla.fun

[payment]
payment.vinaymukkamalla.fun

[frontend]
frontend.vinaymukkamalla.fun

[local]
localhost

[local:vars]
; COURSE=Devops with AWS
; DURATION= 3 months 
; TRAINER=Qaiser
NAME= variable from inventory

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

