; [frontend]
; 172.31.30.111

[mongodb]
#mongodb.vinaymukkamalla.fun   #for ec2-instance
localhost # to configure using localhost as we are using ansible pull terraform_data "mongodb" bootstrap etc

[redis]
#redis.vinaymukkamalla.fun    #for ec2-instance  --> we have replaced ec2-instances with ALB's alias name as domain name
localhost # to configure using terraform

[mysql]
#mysql.vinaymukkamalla.fun   #for ec2-instance
localhost # to configure using terraform

[rabbitmq]
#rabbitmq.vinaymukkamalla.fun   #for ec2-instance
localhost # to configure using terraform

[catalogue]
localhost

[cart]
localhost

[user]
localhost

[shipping]
localhost

[payment]
localhost

[frontend]
localhost

[local]
localhost

[local:vars]
; COURSE=Devops with AWS
; DURATION= 3 months 
; TRAINER=Qaiser
NAME= variable from inventory

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

