- name: "{{ component }} server configuration "
  hosts: "{{ component }}"
  become: yes
  roles:
  - "{{ component }}"



  # ansible-playbook -i inventory.ini main.yaml -e "component=mongodb"
  # ansible-playbook -i inventory.ini main.yaml -e "component=redis"
  # ansible-playbook -i inventory.ini main.yaml -e "component=mysql"
  # ansible-playbook -i inventory.ini main.yaml -e "component=rabbitmq"