  - name: install maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app
  
  - name: move target/{{ component }}-1.0.jar file to {{ component }}.jar
    ansible.builtin.command: mv target/{{ component }}-{{ version }}.jar {{ component }}.jar
    args:
      chdir: /app